2019-05-29 22:24:24,598 ERROR: Exception on /user/Susan [GET] [in /home/user/python_work/flask_web/flask/venv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/user/python_work/flask_web/flask/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python_work/flask_web/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/python_work/flask_web/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/python_work/flask_web/flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/user/python_work/flask_web/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/python_work/flask_web/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/python_work/flask_web/flask/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/user/python_work/flask_web/flask/app/routes.py", line 120, in user
    return render_template('user.html',user=user,posts=posts,next_url=next_url, prev_url=prev_url)
  File "/home/user/python_work/flask_web/flask/venv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/user/python_work/flask_web/flask/venv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/user/python_work/flask_web/flask/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/user/python_work/flask_web/flask/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/user/python_work/flask_web/flask/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/python_work/flask_web/flask/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/user/python_work/flask_web/flask/app/templates/user.html", line 1, in top-level template code
    {% extends 'base.html'%}
  File "/home/user/python_work/flask_web/flask/app/templates/base.html", line 32, in top-level template code
    {% block content %} {% endblock %}
  File "/home/user/python_work/flask_web/flask/app/templates/user.html", line 26, in block "content"
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2019-05-29 22:26:30,995 INFO: MicroBlog Start [in /home/user/python_work/flask_web/flask/app/error.py:72]
2019-05-29 22:26:33,731 ERROR: Exception on /user/Susan [GET] [in /home/user/python_work/flask_web/flask/venv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/user/python_work/flask_web/flask/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/python_work/flask_web/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/python_work/flask_web/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/python_work/flask_web/flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/user/python_work/flask_web/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/python_work/flask_web/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/python_work/flask_web/flask/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/user/python_work/flask_web/flask/app/routes.py", line 120, in user
    return render_template('user.html',user=user,posts=posts,next_url=next_url, prev_url=prev_url)
  File "/home/user/python_work/flask_web/flask/venv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/user/python_work/flask_web/flask/venv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/user/python_work/flask_web/flask/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/user/python_work/flask_web/flask/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/user/python_work/flask_web/flask/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/python_work/flask_web/flask/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/user/python_work/flask_web/flask/app/templates/user.html", line 1, in top-level template code
    {% extends 'base.html'%}
  File "/home/user/python_work/flask_web/flask/app/templates/base.html", line 32, in top-level template code
    {% block content %} {% endblock %}
  File "/home/user/python_work/flask_web/flask/app/templates/user.html", line 26, in block "content"
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2019-05-29 22:27:32,267 INFO: MicroBlog Start [in /home/user/python_work/flask_web/flask/app/error.py:72]
2019-05-29 22:32:07,843 INFO: MicroBlog Start [in /home/user/python_work/flask_web/flask/app/error.py:72]
2019-05-29 22:34:38,515 INFO: MicroBlog Start [in /home/user/python_work/flask_web/flask/app/error.py:72]
2019-05-29 22:36:08,280 INFO: MicroBlog Start [in /home/user/python_work/flask_web/flask/app/error.py:72]
